### ISSUE TITLE
Issue with valid card number (according to Luhn) but unknown vendor

### ISSUE THREAD

**Issue by intrueder** [kozakdenys/kottans-cards#5]
Vendor for `35301113333000001` has been recognized as `Unknown` (correct, 17 digits instead of 16 for JCB)
Such number should not pass validation, but it passes.

**Comment by kozakdenys** [comment]
I don't understand.
Why this number should  not pass validation? This number is valid (Luhn algorithm says that).

**Comment by intrueder** [comment]
Luhn algorithm is used widely, not only in credit cards validation scenarios. In our case we should validate credit card numbers only, not any kind of digit series. Do you agree?
